<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <DefaultItemExcludes>$(DefaultItemExcludes);bin\**;obj\**;.artifacts\**;.tempbin\**;.tempobj\**</DefaultItemExcludes>
  </PropertyGroup>

</Project>
