// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartPOS.Infrastructure.Data;

#nullable disable

namespace SmartPOS.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260205083355_AddTables")]
    partial class AddTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("SmartPOS.Core.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ColorCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("IconName")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ColorCode = "#4CAF50",
                            CreatedAt = new DateTime(2026, 2, 5, 10, 33, 54, 653, DateTimeKind.Local).AddTicks(6861),
                            Description = "المواد الغذائية والمشروبات",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "مواد غذائية"
                        },
                        new
                        {
                            Id = 2,
                            ColorCode = "#2196F3",
                            CreatedAt = new DateTime(2026, 2, 5, 10, 33, 54, 653, DateTimeKind.Local).AddTicks(6861),
                            Description = "المشروبات الساخنة والباردة",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "مشروبات"
                        },
                        new
                        {
                            Id = 3,
                            ColorCode = "#FF9800",
                            CreatedAt = new DateTime(2026, 2, 5, 10, 33, 54, 653, DateTimeKind.Local).AddTicks(6861),
                            Description = "الحلويات والشوكولاتة",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "حلويات"
                        },
                        new
                        {
                            Id = 4,
                            ColorCode = "#9C27B0",
                            CreatedAt = new DateTime(2026, 2, 5, 10, 33, 54, 653, DateTimeKind.Local).AddTicks(6861),
                            Description = "منتجات الألبان والأجبان",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "ألبان"
                        },
                        new
                        {
                            Id = 5,
                            ColorCode = "#F44336",
                            CreatedAt = new DateTime(2026, 2, 5, 10, 33, 54, 653, DateTimeKind.Local).AddTicks(6861),
                            Description = "الأطعمة المعلبة",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "معلبات"
                        },
                        new
                        {
                            Id = 6,
                            ColorCode = "#795548",
                            CreatedAt = new DateTime(2026, 2, 5, 10, 33, 54, 653, DateTimeKind.Local).AddTicks(6861),
                            Description = "وجبات مطعم وكافيه",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "وجبات"
                        });
                });

            modelBuilder.Entity("SmartPOS.Core.Entities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Birthdate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CreditLimit")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CurrentDebt")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "--",
                            CreatedAt = new DateTime(2026, 2, 5, 10, 33, 54, 653, DateTimeKind.Local).AddTicks(6861),
                            CreditLimit = 0m,
                            CurrentDebt = 0m,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "عميل نقدي",
                            Phone = "0100000000"
                        },
                        new
                        {
                            Id = 2,
                            Address = "القاهرة",
                            CreatedAt = new DateTime(2026, 2, 5, 10, 33, 54, 653, DateTimeKind.Local).AddTicks(6861),
                            CreditLimit = 5000m,
                            CurrentDebt = 0m,
                            Email = "sales@alhuda.com",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "شركة الهدى",
                            Phone = "0101234567"
                        });
                });

            modelBuilder.Entity("SmartPOS.Core.Entities.CustomerLoyalty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("CustomerId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastTierUpdate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Points")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Tier")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalPointsEarned")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalPointsRedeemed")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId")
                        .IsUnique();

                    b.ToTable("CustomerLoyalties");
                });

            modelBuilder.Entity("SmartPOS.Core.Entities.Expense", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("Category")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpenseDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("Receipt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ExpenseDate");

                    b.HasIndex("UserId");

                    b.ToTable("Expenses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 500.00m,
                            Category = 2,
                            CreatedAt = new DateTime(2026, 1, 31, 10, 33, 54, 653, DateTimeKind.Local).AddTicks(6861),
                            Description = "فاتورة كهرباء - يناير",
                            ExpenseDate = new DateTime(2026, 1, 31, 10, 33, 54, 653, DateTimeKind.Local).AddTicks(6861),
                            IsDeleted = false,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            Amount = 350.00m,
                            Category = 5,
                            CreatedAt = new DateTime(2026, 2, 2, 10, 33, 54, 653, DateTimeKind.Local).AddTicks(6861),
                            Description = "صيانة ثلاجة العرض",
                            ExpenseDate = new DateTime(2026, 2, 2, 10, 33, 54, 653, DateTimeKind.Local).AddTicks(6861),
                            IsDeleted = false,
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            Amount = 1500.00m,
                            Category = 3,
                            CreatedAt = new DateTime(2026, 2, 3, 10, 33, 54, 653, DateTimeKind.Local).AddTicks(6861),
                            Description = "مرتب عامل نظافة",
                            ExpenseDate = new DateTime(2026, 2, 3, 10, 33, 54, 653, DateTimeKind.Local).AddTicks(6861),
                            IsDeleted = false,
                            UserId = 1
                        },
                        new
                        {
                            Id = 4,
                            Amount = 150.00m,
                            Category = 4,
                            CreatedAt = new DateTime(2026, 2, 4, 10, 33, 54, 653, DateTimeKind.Local).AddTicks(6861),
                            Description = "أكياس بلاستيك",
                            ExpenseDate = new DateTime(2026, 2, 4, 10, 33, 54, 653, DateTimeKind.Local).AddTicks(6861),
                            IsDeleted = false,
                            UserId = 1
                        });
                });

            modelBuilder.Entity("SmartPOS.Core.Entities.LoyaltyTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("CustomerLoyaltyId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Points")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("RelatedAmount")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SaleId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CustomerLoyaltyId");

                    b.HasIndex("SaleId");

                    b.ToTable("LoyaltyTransactions");
                });

            modelBuilder.Entity("SmartPOS.Core.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImagePath")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MinStockLevel")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PurchasePrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SellingPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("Stock")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SupplierId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Unit")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Barcode");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Name");

                    b.HasIndex("SupplierId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Barcode = "1001",
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 2, 5, 10, 33, 54, 653, DateTimeKind.Local).AddTicks(6861),
                            IsActive = true,
                            IsDeleted = false,
                            MinStockLevel = 10,
                            Name = "أرز أبيض - كيس 1 كجم",
                            PurchasePrice = 15.00m,
                            SellingPrice = 20.00m,
                            Stock = 50,
                            SupplierId = 1,
                            Unit = 4
                        },
                        new
                        {
                            Id = 2,
                            Barcode = "1002",
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 2, 5, 10, 33, 54, 653, DateTimeKind.Local).AddTicks(6861),
                            IsActive = true,
                            IsDeleted = false,
                            MinStockLevel = 15,
                            Name = "سكر أبيض - كيس 1 كجم",
                            PurchasePrice = 18.00m,
                            SellingPrice = 25.00m,
                            Stock = 45,
                            SupplierId = 1,
                            Unit = 4
                        },
                        new
                        {
                            Id = 3,
                            Barcode = "1003",
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 2, 5, 10, 33, 54, 653, DateTimeKind.Local).AddTicks(6861),
                            IsActive = true,
                            IsDeleted = false,
                            MinStockLevel = 10,
                            Name = "زيت طعام - زجاجة 1 لتر",
                            PurchasePrice = 35.00m,
                            SellingPrice = 45.00m,
                            Stock = 30,
                            SupplierId = 1,
                            Unit = 5
                        },
                        new
                        {
                            Id = 4,
                            Barcode = "1004",
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 2, 5, 10, 33, 54, 653, DateTimeKind.Local).AddTicks(6861),
                            IsActive = true,
                            IsDeleted = false,
                            MinStockLevel = 20,
                            Name = "مكرونة إسباجتي - علبة 500جم",
                            PurchasePrice = 8.00m,
                            SellingPrice = 12.00m,
                            Stock = 60,
                            SupplierId = 1,
                            Unit = 2
                        },
                        new
                        {
                            Id = 5,
                            Barcode = "1005",
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 2, 5, 10, 33, 54, 653, DateTimeKind.Local).AddTicks(6861),
                            IsActive = true,
                            IsDeleted = false,
                            MinStockLevel = 10,
                            Name = "طحين أبيض - كيس 1 كجم",
                            PurchasePrice = 10.00m,
                            SellingPrice = 15.00m,
                            Stock = 8,
                            SupplierId = 1,
                            Unit = 4
                        },
                        new
                        {
                            Id = 6,
                            Barcode = "2001",
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 2, 5, 10, 33, 54, 653, DateTimeKind.Local).AddTicks(6861),
                            IsActive = true,
                            IsDeleted = false,
                            MinStockLevel = 30,
                            Name = "كوكاكولا - علبة 330 مل",
                            PurchasePrice = 4.00m,
                            SellingPrice = 7.00m,
                            Stock = 100,
                            SupplierId = 2,
                            Unit = 1
                        },
                        new
                        {
                            Id = 7,
                            Barcode = "2002",
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 2, 5, 10, 33, 54, 653, DateTimeKind.Local).AddTicks(6861),
                            IsActive = true,
                            IsDeleted = false,
                            MinStockLevel = 15,
                            Name = "عصير برتقال - عبوة 1 لتر",
                            PurchasePrice = 12.00m,
                            SellingPrice = 18.00m,
                            Stock = 40,
                            SupplierId = 2,
                            Unit = 5
                        },
                        new
                        {
                            Id = 8,
                            Barcode = "2003",
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 2, 5, 10, 33, 54, 653, DateTimeKind.Local).AddTicks(6861),
                            IsActive = true,
                            IsDeleted = false,
                            MinStockLevel = 25,
                            Name = "ماء معدني - زجاجة 1.5 لتر",
                            PurchasePrice = 3.00m,
                            SellingPrice = 5.00m,
                            Stock = 80,
                            SupplierId = 2,
                            Unit = 5
                        },
                        new
                        {
                            Id = 9,
                            Barcode = "2004",
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 2, 5, 10, 33, 54, 653, DateTimeKind.Local).AddTicks(6861),
                            IsActive = true,
                            IsDeleted = false,
                            MinStockLevel = 10,
                            Name = "شاي ليبتون - علبة 100 كيس",
                            PurchasePrice = 25.00m,
                            SellingPrice = 35.00m,
                            Stock = 5,
                            SupplierId = 2,
                            Unit = 2
                        },
                        new
                        {
                            Id = 10,
                            Barcode = "2005",
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 2, 5, 10, 33, 54, 653, DateTimeKind.Local).AddTicks(6861),
                            IsActive = true,
                            IsDeleted = false,
                            MinStockLevel = 8,
                            Name = "قهوة نسكافيه - برطمان 200 جم",
                            PurchasePrice = 40.00m,
                            SellingPrice = 55.00m,
                            Stock = 25,
                            SupplierId = 2,
                            Unit = 1
                        },
                        new
                        {
                            Id = 11,
                            Barcode = "3001",
                            CategoryId = 3,
                            CreatedAt = new DateTime(2026, 2, 5, 10, 33, 54, 653, DateTimeKind.Local).AddTicks(6861),
                            IsActive = true,
                            IsDeleted = false,
                            MinStockLevel = 20,
                            Name = "شوكولاتة كيت كات",
                            PurchasePrice = 5.00m,
                            SellingPrice = 8.00m,
                            Stock = 70,
                            SupplierId = 1,
                            Unit = 1
                        },
                        new
                        {
                            Id = 12,
                            Barcode = "3002",
                            CategoryId = 3,
                            CreatedAt = new DateTime(2026, 2, 5, 10, 33, 54, 653, DateTimeKind.Local).AddTicks(6861),
                            IsActive = true,
                            IsDeleted = false,
                            MinStockLevel = 15,
                            Name = "بسكويت أوريو",
                            PurchasePrice = 6.00m,
                            SellingPrice = 10.00m,
                            Stock = 55,
                            SupplierId = 1,
                            Unit = 2
                        },
                        new
                        {
                            Id = 13,
                            Barcode = "3003",
                            CategoryId = 3,
                            CreatedAt = new DateTime(2026, 2, 5, 10, 33, 54, 653, DateTimeKind.Local).AddTicks(6861),
                            IsActive = true,
                            IsDeleted = false,
                            MinStockLevel = 30,
                            Name = "حلوى جيلي - كيس صغير",
                            PurchasePrice = 2.00m,
                            SellingPrice = 4.00m,
                            Stock = 90,
                            SupplierId = 1,
                            Unit = 1
                        },
                        new
                        {
                            Id = 14,
                            Barcode = "4001",
                            CategoryId = 4,
                            CreatedAt = new DateTime(2026, 2, 5, 10, 33, 54, 653, DateTimeKind.Local).AddTicks(6861),
                            IsActive = true,
                            IsDeleted = false,
                            MinStockLevel = 15,
                            Name = "لبن كامل الدسم - كرتونة 1 لتر",
                            PurchasePrice = 15.00m,
                            SellingPrice = 20.00m,
                            Stock = 35,
                            SupplierId = 1,
                            Unit = 5
                        },
                        new
                        {
                            Id = 15,
                            Barcode = "4002",
                            CategoryId = 4,
                            CreatedAt = new DateTime(2026, 2, 5, 10, 33, 54, 653, DateTimeKind.Local).AddTicks(6861),
                            IsActive = true,
                            IsDeleted = false,
                            MinStockLevel = 10,
                            Name = "جبنة بيضاء - علبة 500 جم",
                            PurchasePrice = 30.00m,
                            SellingPrice = 40.00m,
                            Stock = 20,
                            SupplierId = 1,
                            Unit = 2
                        },
                        new
                        {
                            Id = 16,
                            Barcode = "4003",
                            CategoryId = 4,
                            CreatedAt = new DateTime(2026, 2, 5, 10, 33, 54, 653, DateTimeKind.Local).AddTicks(6861),
                            IsActive = true,
                            IsDeleted = false,
                            MinStockLevel = 20,
                            Name = "زبادي فواكه - علبة صغيرة",
                            PurchasePrice = 4.00m,
                            SellingPrice = 6.00m,
                            Stock = 45,
                            SupplierId = 1,
                            Unit = 1
                        },
                        new
                        {
                            Id = 17,
                            Barcode = "5001",
                            CategoryId = 5,
                            CreatedAt = new DateTime(2026, 2, 5, 10, 33, 54, 653, DateTimeKind.Local).AddTicks(6861),
                            IsActive = true,
                            IsDeleted = false,
                            MinStockLevel = 15,
                            Name = "تونة - علبة متوسطة",
                            PurchasePrice = 12.00m,
                            SellingPrice = 18.00m,
                            Stock = 40,
                            SupplierId = 1,
                            Unit = 2
                        },
                        new
                        {
                            Id = 18,
                            Barcode = "5002",
                            CategoryId = 5,
                            CreatedAt = new DateTime(2026, 2, 5, 10, 33, 54, 653, DateTimeKind.Local).AddTicks(6861),
                            IsActive = true,
                            IsDeleted = false,
                            MinStockLevel = 20,
                            Name = "فول مدمس - علبة 400 جم",
                            PurchasePrice = 8.00m,
                            SellingPrice = 12.00m,
                            Stock = 50,
                            SupplierId = 1,
                            Unit = 2
                        },
                        new
                        {
                            Id = 19,
                            Barcode = "5003",
                            CategoryId = 5,
                            CreatedAt = new DateTime(2026, 2, 5, 10, 33, 54, 653, DateTimeKind.Local).AddTicks(6861),
                            IsActive = true,
                            IsDeleted = false,
                            MinStockLevel = 10,
                            Name = "طماطم معجون - علبة 400 جم",
                            PurchasePrice = 7.00m,
                            SellingPrice = 10.00m,
                            Stock = 3,
                            SupplierId = 1,
                            Unit = 2
                        },
                        new
                        {
                            Id = 20,
                            Barcode = "5004",
                            CategoryId = 5,
                            CreatedAt = new DateTime(2026, 2, 5, 10, 33, 54, 653, DateTimeKind.Local).AddTicks(6861),
                            IsActive = true,
                            IsDeleted = false,
                            MinStockLevel = 10,
                            Name = "ذرة حلوة - علبة 340 جم",
                            PurchasePrice = 9.00m,
                            SellingPrice = 13.00m,
                            Stock = 6,
                            SupplierId = 1,
                            Unit = 2
                        },
                        new
                        {
                            Id = 21,
                            Barcode = "6001",
                            CategoryId = 6,
                            CreatedAt = new DateTime(2026, 2, 5, 10, 33, 54, 653, DateTimeKind.Local).AddTicks(6861),
                            IsActive = true,
                            IsDeleted = false,
                            MinStockLevel = 10,
                            Name = "برجر كلاسيك",
                            PurchasePrice = 25.00m,
                            SellingPrice = 40.00m,
                            Stock = 30,
                            SupplierId = 1,
                            Unit = 1
                        },
                        new
                        {
                            Id = 22,
                            Barcode = "6002",
                            CategoryId = 6,
                            CreatedAt = new DateTime(2026, 2, 5, 10, 33, 54, 653, DateTimeKind.Local).AddTicks(6861),
                            IsActive = true,
                            IsDeleted = false,
                            MinStockLevel = 8,
                            Name = "بيتزا مارجريتا",
                            PurchasePrice = 35.00m,
                            SellingPrice = 55.00m,
                            Stock = 20,
                            SupplierId = 1,
                            Unit = 1
                        },
                        new
                        {
                            Id = 23,
                            Barcode = "6003",
                            CategoryId = 6,
                            CreatedAt = new DateTime(2026, 2, 5, 10, 33, 54, 653, DateTimeKind.Local).AddTicks(6861),
                            IsActive = true,
                            IsDeleted = false,
                            MinStockLevel = 15,
                            Name = "ساندوتش شاورما",
                            PurchasePrice = 18.00m,
                            SellingPrice = 30.00m,
                            Stock = 40,
                            SupplierId = 1,
                            Unit = 1
                        },
                        new
                        {
                            Id = 24,
                            Barcode = "6004",
                            CategoryId = 6,
                            CreatedAt = new DateTime(2026, 2, 5, 10, 33, 54, 653, DateTimeKind.Local).AddTicks(6861),
                            IsActive = true,
                            IsDeleted = false,
                            MinStockLevel = 10,
                            Name = "وجبة فطار",
                            PurchasePrice = 20.00m,
                            SellingPrice = 35.00m,
                            Stock = 25,
                            SupplierId = 1,
                            Unit = 1
                        });
                });

            modelBuilder.Entity("SmartPOS.Core.Entities.PurchaseOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PaidAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ReceivedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SupplierId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OrderNumber")
                        .IsUnique();

                    b.HasIndex("SupplierId");

                    b.ToTable("PurchaseOrders");
                });

            modelBuilder.Entity("SmartPOS.Core.Entities.Return", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("CustomerId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRefunded")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProcessedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Reason")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("RefundDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ReturnDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReturnNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("SaleId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ProcessedByUserId");

                    b.HasIndex("SaleId");

                    b.ToTable("Returns");
                });

            modelBuilder.Entity("SmartPOS.Core.Entities.ReturnDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Reason")
                        .HasColumnType("TEXT");

                    b.Property<int>("ReturnId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Subtotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("ReturnId");

                    b.ToTable("ReturnDetails");
                });

            modelBuilder.Entity("SmartPOS.Core.Entities.Sale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AmountPaid")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ChangeAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("DiscountAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DiscountPercentage")
                        .HasColumnType("TEXT");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPrinted")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LoyaltyPointsEarned")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LoyaltyPointsRedeemed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int>("PaymentMethod")
                        .HasColumnType("INTEGER");

                    b.Property<string>("QRCode")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SaleDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ShiftId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Subtotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TaxAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("InvoiceNumber")
                        .IsUnique();

                    b.HasIndex("SaleDate");

                    b.HasIndex("ShiftId");

                    b.HasIndex("UserId");

                    b.ToTable("Sales");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AmountPaid = 70m,
                            ChangeAmount = 0m,
                            CreatedAt = new DateTime(2026, 2, 5, 9, 33, 54, 653, DateTimeKind.Local).AddTicks(6861),
                            CustomerId = 1,
                            DiscountAmount = 0m,
                            DiscountPercentage = 0m,
                            InvoiceNumber = "INV-20260205-0001",
                            IsDeleted = false,
                            IsPrinted = false,
                            PaymentMethod = 1,
                            SaleDate = new DateTime(2026, 2, 5, 9, 33, 54, 653, DateTimeKind.Local).AddTicks(6861),
                            Status = 2,
                            Subtotal = 70m,
                            TaxAmount = 0m,
                            TotalAmount = 70m,
                            UserId = 2
                        },
                        new
                        {
                            Id = 2,
                            AmountPaid = 50m,
                            ChangeAmount = 0m,
                            CreatedAt = new DateTime(2026, 2, 4, 8, 33, 54, 653, DateTimeKind.Local).AddTicks(6861),
                            CustomerId = 1,
                            DiscountAmount = 5m,
                            DiscountPercentage = 0m,
                            InvoiceNumber = "INV-20260204-0002",
                            IsDeleted = false,
                            IsPrinted = false,
                            PaymentMethod = 1,
                            SaleDate = new DateTime(2026, 2, 4, 8, 33, 54, 653, DateTimeKind.Local).AddTicks(6861),
                            Status = 2,
                            Subtotal = 55m,
                            TaxAmount = 0m,
                            TotalAmount = 50m,
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            AmountPaid = 68m,
                            ChangeAmount = 0m,
                            CreatedAt = new DateTime(2026, 2, 3, 7, 33, 54, 653, DateTimeKind.Local).AddTicks(6861),
                            CustomerId = 2,
                            DiscountAmount = 0m,
                            DiscountPercentage = 0m,
                            InvoiceNumber = "INV-20260203-0003",
                            IsDeleted = false,
                            IsPrinted = false,
                            PaymentMethod = 2,
                            SaleDate = new DateTime(2026, 2, 3, 7, 33, 54, 653, DateTimeKind.Local).AddTicks(6861),
                            Status = 2,
                            Subtotal = 68m,
                            TaxAmount = 0m,
                            TotalAmount = 68m,
                            UserId = 2
                        });
                });

            modelBuilder.Entity("SmartPOS.Core.Entities.SaleDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DiscountAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DiscountPercentage")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("LineTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SaleId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("UnitCost")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("SaleId");

                    b.ToTable("SaleDetails");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 2, 5, 9, 33, 54, 653, DateTimeKind.Local).AddTicks(6861),
                            DiscountAmount = 0m,
                            DiscountPercentage = 0m,
                            IsDeleted = false,
                            LineTotal = 40m,
                            ProductId = 1,
                            Quantity = 2,
                            SaleId = 1,
                            UnitCost = 15m,
                            UnitPrice = 20m
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 2, 5, 9, 33, 54, 653, DateTimeKind.Local).AddTicks(6861),
                            DiscountAmount = 0m,
                            DiscountPercentage = 0m,
                            IsDeleted = false,
                            LineTotal = 14m,
                            ProductId = 6,
                            Quantity = 2,
                            SaleId = 1,
                            UnitCost = 4m,
                            UnitPrice = 7m
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 2, 5, 9, 33, 54, 653, DateTimeKind.Local).AddTicks(6861),
                            DiscountAmount = 0m,
                            DiscountPercentage = 0m,
                            IsDeleted = false,
                            LineTotal = 16m,
                            ProductId = 11,
                            Quantity = 2,
                            SaleId = 1,
                            UnitCost = 5m,
                            UnitPrice = 8m
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 2, 4, 8, 33, 54, 653, DateTimeKind.Local).AddTicks(6861),
                            DiscountAmount = 0m,
                            DiscountPercentage = 0m,
                            IsDeleted = false,
                            LineTotal = 45m,
                            ProductId = 3,
                            Quantity = 1,
                            SaleId = 2,
                            UnitCost = 35m,
                            UnitPrice = 45m
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 2, 4, 8, 33, 54, 653, DateTimeKind.Local).AddTicks(6861),
                            DiscountAmount = 0m,
                            DiscountPercentage = 0m,
                            IsDeleted = false,
                            LineTotal = 10m,
                            ProductId = 8,
                            Quantity = 2,
                            SaleId = 2,
                            UnitCost = 3m,
                            UnitPrice = 5m
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 2, 3, 7, 33, 54, 653, DateTimeKind.Local).AddTicks(6861),
                            DiscountAmount = 0m,
                            DiscountPercentage = 0m,
                            IsDeleted = false,
                            LineTotal = 40m,
                            ProductId = 15,
                            Quantity = 1,
                            SaleId = 3,
                            UnitCost = 30m,
                            UnitPrice = 40m
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2026, 2, 3, 7, 33, 54, 653, DateTimeKind.Local).AddTicks(6861),
                            DiscountAmount = 0m,
                            DiscountPercentage = 0m,
                            IsDeleted = false,
                            LineTotal = 10m,
                            ProductId = 12,
                            Quantity = 1,
                            SaleId = 3,
                            UnitCost = 6m,
                            UnitPrice = 10m
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2026, 2, 3, 7, 33, 54, 653, DateTimeKind.Local).AddTicks(6861),
                            DiscountAmount = 0m,
                            DiscountPercentage = 0m,
                            IsDeleted = false,
                            LineTotal = 18m,
                            ProductId = 7,
                            Quantity = 1,
                            SaleId = 3,
                            UnitCost = 12m,
                            UnitPrice = 18m
                        });
                });

            modelBuilder.Entity("SmartPOS.Core.Entities.Shift", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("ClosingBalance")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Difference")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("ExpectedBalance")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("OpeningBalance")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Shifts");
                });

            modelBuilder.Entity("SmartPOS.Core.Entities.StockMovement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("MovementDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Reference")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MovementDate");

                    b.HasIndex("ProductId");

                    b.ToTable("StockMovements");
                });

            modelBuilder.Entity("SmartPOS.Core.Entities.Supplier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContactPerson")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DebtAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Suppliers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 2, 5, 10, 33, 54, 653, DateTimeKind.Local).AddTicks(6861),
                            DebtAmount = 0m,
                            Email = "info@egyptfood.com",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "شركة الأغذية المصرية",
                            Phone = "0123456789"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 2, 5, 10, 33, 54, 653, DateTimeKind.Local).AddTicks(6861),
                            DebtAmount = 0m,
                            Email = "sales@drinks.com",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "مورد المشروبات الوطنية",
                            Phone = "0111222333"
                        });
                });

            modelBuilder.Entity("SmartPOS.Core.Entities.Table", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Capacity")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CurrentOrderId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Section")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Tables");
                });

            modelBuilder.Entity("SmartPOS.Core.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 2, 5, 10, 33, 54, 653, DateTimeKind.Local).AddTicks(6861),
                            FullName = "مدير النظام",
                            IsActive = true,
                            IsDeleted = false,
                            PasswordHash = "$2a$11$X7X8X9X0X1X2X3X4X5X6X7X8X9X0X1X2X3X4X5X6X7X8X9X0X1X2",
                            Role = 1,
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 2, 5, 10, 33, 54, 653, DateTimeKind.Local).AddTicks(6861),
                            FullName = "أحمد محمود - كاشير",
                            IsActive = true,
                            IsDeleted = false,
                            PasswordHash = "$2a$11$X7X8X9X0X1X2X3X4X5X6X7X8X9X0X1X2X3X4X5X6X7X8X9X0X1X2",
                            Role = 3,
                            Username = "cashier1"
                        });
                });

            modelBuilder.Entity("SmartPOS.Core.Entities.CustomerLoyalty", b =>
                {
                    b.HasOne("SmartPOS.Core.Entities.Customer", "Customer")
                        .WithOne("Loyalty")
                        .HasForeignKey("SmartPOS.Core.Entities.CustomerLoyalty", "CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("SmartPOS.Core.Entities.Expense", b =>
                {
                    b.HasOne("SmartPOS.Core.Entities.User", "User")
                        .WithMany("Expenses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartPOS.Core.Entities.LoyaltyTransaction", b =>
                {
                    b.HasOne("SmartPOS.Core.Entities.CustomerLoyalty", "CustomerLoyalty")
                        .WithMany("Transactions")
                        .HasForeignKey("CustomerLoyaltyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartPOS.Core.Entities.Sale", "Sale")
                        .WithMany("LoyaltyTransactions")
                        .HasForeignKey("SaleId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CustomerLoyalty");

                    b.Navigation("Sale");
                });

            modelBuilder.Entity("SmartPOS.Core.Entities.Product", b =>
                {
                    b.HasOne("SmartPOS.Core.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartPOS.Core.Entities.Supplier", "Supplier")
                        .WithMany("Products")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Category");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("SmartPOS.Core.Entities.PurchaseOrder", b =>
                {
                    b.HasOne("SmartPOS.Core.Entities.Supplier", "Supplier")
                        .WithMany("PurchaseOrders")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("SmartPOS.Core.Entities.Return", b =>
                {
                    b.HasOne("SmartPOS.Core.Entities.Customer", "Customer")
                        .WithMany("Returns")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartPOS.Core.Entities.User", "ProcessedBy")
                        .WithMany()
                        .HasForeignKey("ProcessedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartPOS.Core.Entities.Sale", "Sale")
                        .WithMany("Returns")
                        .HasForeignKey("SaleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("ProcessedBy");

                    b.Navigation("Sale");
                });

            modelBuilder.Entity("SmartPOS.Core.Entities.ReturnDetail", b =>
                {
                    b.HasOne("SmartPOS.Core.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartPOS.Core.Entities.Return", "Return")
                        .WithMany("ReturnDetails")
                        .HasForeignKey("ReturnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Return");
                });

            modelBuilder.Entity("SmartPOS.Core.Entities.Sale", b =>
                {
                    b.HasOne("SmartPOS.Core.Entities.Customer", "Customer")
                        .WithMany("Sales")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SmartPOS.Core.Entities.Shift", "Shift")
                        .WithMany("Sales")
                        .HasForeignKey("ShiftId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SmartPOS.Core.Entities.User", "User")
                        .WithMany("Sales")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Shift");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartPOS.Core.Entities.SaleDetail", b =>
                {
                    b.HasOne("SmartPOS.Core.Entities.Product", "Product")
                        .WithMany("SaleDetails")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartPOS.Core.Entities.Sale", "Sale")
                        .WithMany("SaleDetails")
                        .HasForeignKey("SaleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Sale");
                });

            modelBuilder.Entity("SmartPOS.Core.Entities.Shift", b =>
                {
                    b.HasOne("SmartPOS.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartPOS.Core.Entities.StockMovement", b =>
                {
                    b.HasOne("SmartPOS.Core.Entities.Product", "Product")
                        .WithMany("StockMovements")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("SmartPOS.Core.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("SmartPOS.Core.Entities.Customer", b =>
                {
                    b.Navigation("Loyalty");

                    b.Navigation("Returns");

                    b.Navigation("Sales");
                });

            modelBuilder.Entity("SmartPOS.Core.Entities.CustomerLoyalty", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("SmartPOS.Core.Entities.Product", b =>
                {
                    b.Navigation("SaleDetails");

                    b.Navigation("StockMovements");
                });

            modelBuilder.Entity("SmartPOS.Core.Entities.Return", b =>
                {
                    b.Navigation("ReturnDetails");
                });

            modelBuilder.Entity("SmartPOS.Core.Entities.Sale", b =>
                {
                    b.Navigation("LoyaltyTransactions");

                    b.Navigation("Returns");

                    b.Navigation("SaleDetails");
                });

            modelBuilder.Entity("SmartPOS.Core.Entities.Shift", b =>
                {
                    b.Navigation("Sales");
                });

            modelBuilder.Entity("SmartPOS.Core.Entities.Supplier", b =>
                {
                    b.Navigation("Products");

                    b.Navigation("PurchaseOrders");
                });

            modelBuilder.Entity("SmartPOS.Core.Entities.User", b =>
                {
                    b.Navigation("Expenses");

                    b.Navigation("Sales");
                });
#pragma warning restore 612, 618
        }
    }
}
